"""empty message

Revision ID: 0ac55ca62d28
Revises: 
Create Date: 2025-10-02 10:44:31.623486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac55ca62d28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pontos', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('jogos_disputados', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vitorias', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('empates', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('derrotas', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gols_pro', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gols_contra', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('saldo_gols', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classificacao', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('saldo_gols')
        batch_op.drop_column('gols_contra')
        batch_op.drop_column('gols_pro')
        batch_op.drop_column('derrotas')
        batch_op.drop_column('empates')
        batch_op.drop_column('vitorias')
        batch_op.drop_column('jogos_disputados')
        batch_op.drop_column('pontos')

    # ### end Alembic commands ###
