from .competicao_controller import CompeticaoController
from .treinador_controller import TreinadorController
from .time_controller import TimeController
from .jogador_controller import JogadorController
from .jogo_controller import JogoController